### ISSUE TITLE
Single-key instantiation

### ISSUE THREAD

**Issue by pdl** [pdl/Articulate#26]
It would be good if single-key hashrefs could be instantiated as class+args, so all these mean the same:

```yaml
- Articulate::Class
- Articulate::Class: {}
- class: Articulate::Class
  args: {}
```
